### ISSUE TITLE
Starting lux-ai-2021 without parameters throws exception

### ISSUE THREAD

**Issue by Gerenuk** [Lux-AI-Challenge/Lux-Design-2021#112]
Starting `lux-ai-2021` (version 2.1.0) without parameters throws an exception

```
> lux-ai-2021
node_modules/lib/node_modules/@lux-ai/2021-challenge/lib/es5/bin/runner.js:32
throw Error('Need two paths to agents');
```

A gentle error message would probably be better.

**Comment by StoneT2000** [comment]
Wait actually, that's exactly the correct error message, you do need to provide two paths. Closing this

**Comment by Gerenuk** [comment]
It's indeed the correct message, but wouldn't it be cleaner to show an intended message? Relying on uncaught exceptions for output makes a dirty impression. I believe programmers might get more trust in the robustness, if there are no uncaught exceptions for simple reasons.
