### ISSUE TITLE
Notebook example missing Lux module setup for non-Kaggle environments

### ISSUE THREAD

**Issue by glmcdona** [Lux-AI-Challenge/Lux-Design-2021#119]
Getting Started sends you to the notebook here to set up:
https://www.kaggle.com/stonet2000/lux-ai-season-1-jupyter-notebook-tutorial

Running through this notebook locally (instead of on kaggle) runs into a snag when it comes to:
```from lux.game import Game```

This is because the lux library needs to be copied to the local directory. I'd suggest maybe adding a comment to the cell ahead of it on what to do if you aren't using kaggle notebooks instead of that copy command. (Clone github repo, and copy the folder "/kits/python/simple/lux" into the same folder as the notebook).

**Comment by StoneT2000** [comment]
This is fixed soon, thanks for bringing this up! I've added the usual fix thats in the starter kits.
