### ISSUE TITLE
Visualiser version incompatibility

### ISSUE THREAD

**Issue by kravatma** [Lux-AI-Challenge/Lux-Design-2021#136]
I got this error when try to run visualiser in jupyter notebook from tutorial ([https://www.kaggle.com/stonet2000/lux-ai-season-1-jupyter-notebook-tutorial](https://www.kaggle.com/stonet2000/lux-ai-season-1-jupyter-notebook-tutorial)).
ERROR :
"""
Replay file works on version 3.1.x but client is on version 3.0.1. The visualizer will not be able to parse this replay file. Download an older visualizer with version 3.1.x here to watch the replay: https://github.com/Lux-AI-Challenge/LuxViewer2021/releases
"""
What should I do to fix it?

**Comment by StoneT2000** [comment]
This will be fixed for kaggle environments in about 18 hours.

For now, just follow the instructions given (download the visualizer that matches the version)
