### ISSUE TITLE
Transferring resources is handled sequentially

### ISSUE THREAD

**Issue by lpkirwin** [Lux-AI-Challenge/Lux-Design-2021#30]
It looks like unit actions are handled sequentially in an arbitrary order. This might cause some confusing behaviour where actions that might seem valid/reasonable will silently fail.

Eg if I had:

    worker_1: 80 wood, 20 coal
    worker_2: 20 wood

and I wanted to do two transfers so that worker_1 can go build a city:

    worker_1 --> worker_2: 20 coal
    worker_2 --> worker_1: 20 wood

this may or may not work, depending on the order of execution. If worker_2 did its transfer first, it would silently fail because worker_1 is at capacity.

**Comment by lpkirwin** [comment]
(This is admittedly a pretty minor issue)

**Comment by StoneT2000** [comment]
i suspect that we intend it so you can't do this actually as at the start of the turn any of the resource transfer actions would fail. would be good to add a test for this

**Comment by StoneT2000** [comment]
After discussion we decided that the current implemented behavior is what it will be and this will not change.

**Comment by pcoughlin** [comment]
So is the current implementation to process the Actions "in the order they are pushed into the object"?

**Comment by StoneT2000** [comment]
This is not correct. What happens is all actions are validated in the order they are given such that when actions execute, order does not matter.
