### ISSUE TITLE
Spec updates

### ISSUE THREAD

**Issue by StoneT2000** [Lux-AI-Challenge/Lux-Design-2021#32]
- [x] Clarify that citytiles can do one action a turn
- [x] Refer to road level as a road level in code, not cell cooldown
- [x] Clarify what collection rate means (eg its resources / turn, not turns/resource)
- [x] Clarify that transferring resources will transfer as much as possible to worker, then return the remaining to original unit
- [x] Maybe clarify that actions are simultaneously applied to the current state.
- [x] Fix typo with cart road building. cart auto adds 0.5 to the road level of the cell they start on each turn. (not where they end up)

**Comment by StoneT2000** [comment]
Add link to Kits and API

**Comment by LittleAlvinMaker** [comment]
Changes references to "cell cooldown" to "road" in the whole code base, including the kits and the docs #47

**Comment by holypegasus** [comment]
#68
