### ISSUE TITLE
One off errors

### ISSUE THREAD

**Issue by StoneT2000** [Lux-AI-Challenge/Lux-Design-2021#33]
There is a one off error either in the engine, kit, or visualizer.

E.g. visualizer shows the first turn as turn 0 and actually renders the end of the turn 0.
Kits are 1-indexed (due to engine starting at turn 1).

**Comment by StoneT2000** [comment]
Actually looking more into it, the engine runs 361 turns, not 360, and first day/night cycle has an extra turn of day...

**Comment by LittleAlvinMaker** [comment]
I submitted a pull request to remove the extra day in the engine code.
https://github.com/Lux-AI-Challenge/Lux-Design-2021/pull/36
