### ISSUE TITLE
validateCommand() function is hiding at least a few bugs

### ISSUE THREAD

**Issue by LittleAlvinMaker** [Lux-AI-Challenge/Lux-Design-2021#60]
As I originally tried to make sense of the validateCommand() function, I noticed a couple inconsistencies, which at the time I did not know were bugs or not.  Separating the error check from the throwing of the warning in that function would improve readability greatly and would make making changes much easier.

**Comment by LittleAlvinMaker** [comment]
PR #59

**Comment by StoneT2000** [comment]
fixed in #51
