### ISSUE TITLE
js transfer() method

### ISSUE THREAD

**Issue by rooklift** [Lux-AI-Challenge/Lux-Design-2021#72]
The call signature of the js `transfer` method [here](https://github.com/Lux-AI-Challenge/Lux-Design-2021/blob/master/kits/js/simple/lux/game_objects.js#L124) doesn't match the docs.

Also, I suppose it could be simplified down to something like this:

```javascript
  transfer(destUnit, resourceType, amount) {
    let destID = typeof destUnit === "string" ? destUnit : destUnit.id;
    return `t ${this.id} ${destID} ${resourceType} ${amount}`;
  }
```

I've not actually tested this.

**Comment by StoneT2000** [comment]
Oh good catch, thanks! well test it later

**Comment by LittleAlvinMaker** [comment]
PR #78 (basic tests passed)

**Comment by StoneT2000** [comment]
close #78
