### ISSUE TITLE
Publicity / Outreach / Communications / Promotion / Awareness / Media / Education

### ISSUE THREAD

**Issue by coding-to-music** [Lux-AI-Challenge/Lux-Design-2021#80]
## Articles/Blog Posts Ideas (add more)
- Medium
- Dev.to  [BattlecodeExample](https://dev.to/search?q=battlecode) 
- Reddit for each kit
- Reddit forum for the game
- Twitter
- Facebook
- Hacker News
- Alumni Magazines
- Maker Groups and Forums
- ROS (Robot Operation System) groups
- Drones / Racing 
- Tech Ed - High School / Vocation Schools / Aggie schools / Rural schools / Tribes and isolated people / Maker clubs
- Finance Quant and Modeling / Charting forums

**Comment by StoneT2000** [comment]
Thanks for the suggestions!

We do have a twitter and FB at https://twitter.com/LuxAIChallenge and https://www.facebook.com/Lux-AI-Challenge-108307191481441
