### ISSUE TITLE
Fix resource sorting

### ISSUE THREAD

**Issue by StoneT2000** [Lux-AI-Challenge/Lux-Design-2021#84]
https://github.com/Lux-AI-Challenge/Lux-Design-2021/blob/de87b6f41128862c959071991493c8e3948514a8/src/GameMap/index.ts#L36

should use max(this.width, this.height) to sort by a unique number for each tile.

**Comment by holypegasus** [comment]
I understand reasoning behind `max(this.width, this.height)` but how do you use this method?
